language: python

matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.5

cache:
    - pip

install:
    - pip install .
    - pip install -r requirements-test.txt
    - git archive -o git.tar HEAD

script:
    - flake8
    - python -m archive_vfs benchmark .
    - python -m archive_vfs benchmark git.tar
