language: python

matrix:
    include:
        - os: linux
          python: 2.7
        - os: linux
          python: 3.5

cache:
    - pip

install:
    - pip install .
    - pip install --upgrade -r requirements-test.txt

script:
    - flake8
    - pytest
